### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by JustKappaMan**
@tralph3 hi, see commit messages for details :slightly_smiling_face:

### CODE REVIEW

**Comment by tralph3** [comment]
Hi. Thank you for taking the time of converting the var names to snake case. However the imports seem broken. I can't open the program with this PR, it says there's no module "src". That's because you changed the imports from `from config import config` to `from src.config import config`. `src` is not a module, so this fails.

**Comment by JustKappaMan** [comment]
@tralph3 oops, ok. I'll bring imports back to the original state a little bit later. And then you can merge the PR.

**Comment by JustKappaMan** [comment]
@tralph3 done, ready to be merged :slightly_smiling_face:

**Comment by tralph3** [comment]
Sigh... it's a times like this when I *wish* I had written tests for this program. It does seem to be working fine however, I'll merge it.

**Pull request merged**
